controller_list:
  - name: "/mico_arm"
    # action_ns: smooth_arm_controller/trajectory 
    action_ns: joint_velocity_controller/trajectory
    type: FollowJointTrajectory
    joints: 
      - Mico_joint1
      - Mico_joint2
      - Mico_joint3
      - Mico_joint4
      - Mico_joint5
      - Mico_joint6

